version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-https://qw80so04oc0wkcwg0cw8woko.46.202.89.24.sslip.io/api}
        - VITE_ENVIRONMENT=${VITE_ENVIRONMENT:-production}
        - VITE_WS_URL=${VITE_WS_URL:-wss://qw80so04oc0wkcwg0cw8woko.46.202.89.24.sslip.io}
    container_name: pickleballloveall-frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_ENVIRONMENT=production
    expose:
      - "80"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
